#!/bin/bash
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

# Install grc and coreutils
brew install grc coreutils
# Install unrar
brew install unrar
# Install mercurial (hg)
brew install hg
# Install todo.txt
brew install todo-txt
# Install postgresql
brew install postgresql
# Install lua
brew install lua
# Install luajit
brew install luajit
# Install go
brew install go
