#!/bin/bash
# Based on holman's bootstrap file
# bootstrap-mac installs things on a OS X machine.

# Set relevant OS X's settings
. osx/set-defaults.sh

# Assume everyone runs Homebrew
. brew/homebrew

# Run the install
rake install
