#!/bin/bash
# Based on holman's bootstrap file
# bootstrap-mac installs things on a OS X machine.

# Set relevant OS X's settings
. osx/set-defaults.sh

# Assume everyone runs Homebrew and install relevant packages
. brew/homebrew.sh

# Install rvm and needed versions of ruby
. ruby/rvm-install.sh

# Install relevant ruby gems
. ruby/gem-install.sh

# Install relevant python eggs
. python/egg-install.sh

# Install and link other relevant files
rake install
